Web/LearningSystem.Web/Areas/Administration/Controllers/AdminCommentsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningSystem.Common;
using LearningSystem.Data;
using LearningSystem.Models;

namespace LearningSystem.Web.Areas.Administration.Controllers
{
    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class AdminCommentsController : AdminController
    {
        public AdminCommentsController(ILearningSystemData data) 
            : base(data)
        {
        }
        
        public ActionResult Index()
        {
            var comments = this.Data.Comments
                .All()
                .Include(c => c.Author)
                .Include(c => c.StudyMaterial);

            return View(comments.ToList());
        }
        
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);

            if (comment == null)
            {
                return HttpNotFound();
            }

            return View(comment);
        }
        
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return RedirectToAction("Index");
            }

            var comment = this.Data.Comments.GetById(id);

            if (comment == null)
            {
                return HttpNotFound();
            }

            return View(comment);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Comment comment)
        {
            if (ModelState.IsValid)
            {
                this.Data.Context.Entry(comment).State = EntityState.Modified;
                this.Data.SaveChanges();

                return RedirectToAction("Index");
            }

            return View(comment);
        }

        // GET: Administration/Comments/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            var comment = this.Data.Comments.GetById(id);

            if (comment == null)
            {
                return HttpNotFound();
            }

            return View(comment);
        }
        
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            this.Data.Comments.Delete(id);
            this.Data.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                this.Data.Context.Dispose();
            }

            base.Dispose(disposing);
        }
    }
}

Web/LearningSystem.Web/Areas/Administration/Controllers/AdminMaterialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using LearningSystem.Common;
using LearningSystem.Data;
using LearningSystem.Models;

namespace LearningSystem.Web.Areas.Administration.Controllers
{
    [Authorize(Roles = GlobalConstants.AdminRole)]
    public class AdminMaterialsController : Controller
    {
        private LearningSystemDbContext db = new LearningSystemDbContext();

        // GET: Administration/StudyMaterials
        public ActionResult Index()
        {
            var studyMaterials = db.StudyMaterials.Include(s => s.Author).Include(s => s.Section);
            return View(studyMaterials.ToList());
        }

        // GET: Administration/StudyMaterials/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyMaterial studyMaterial = db.StudyMaterials.Find(id);
            if (studyMaterial == null)
            {
                return HttpNotFound();
            }
            return View(studyMaterial);
        }

        // GET: Administration/StudyMaterials/Create
        public ActionResult Create()
        {
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName");
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Title");
            return View();
        }

        // POST: Administration/StudyMaterials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,PublishDate,Content,Description,Source,SectionId,AuthorId")] StudyMaterial studyMaterial)
        {
            if (ModelState.IsValid)
            {
                db.StudyMaterials.Add(studyMaterial);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName", studyMaterial.AuthorId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Title", studyMaterial.SectionId);
            return View(studyMaterial);
        }

        // GET: Administration/StudyMaterials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyMaterial studyMaterial = db.StudyMaterials.Find(id);
            if (studyMaterial == null)
            {
                return HttpNotFound();
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName", studyMaterial.AuthorId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Title", studyMaterial.SectionId);
            return View(studyMaterial);
        }

        // POST: Administration/StudyMaterials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,PublishDate,Content,Description,Source,SectionId,AuthorId")] StudyMaterial studyMaterial)
        {
            if (ModelState.IsValid)
            {
                db.Entry(studyMaterial).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.AuthorId = new SelectList(db.Users, "Id", "FullName", studyMaterial.AuthorId);
            ViewBag.SectionId = new SelectList(db.Sections, "Id", "Title", studyMaterial.SectionId);
            return View(studyMaterial);
        }

        // GET: Administration/StudyMaterials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            StudyMaterial studyMaterial = db.StudyMaterials.Find(id);
            if (studyMaterial == null)
            {
                return HttpNotFound();
            }
            return View(studyMaterial);
        }

        // POST: Administration/StudyMaterials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            StudyMaterial studyMaterial = db.StudyMaterials.Find(id);
            db.StudyMaterials.Remove(studyMaterial);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Web/LearningSystem.Web/Controllers/CertificationController.cs
using System.Web.Mvc;
using LearningSystem.Data;

namespace LearningSystem.Web.Controllers
{
    [RoutePrefix("certificate")]
    public class CertificationController : BaseController
    {
        public CertificationController(ILearningSystemData data)
            :base(data)
        {
        }
        
        [Route("info")]
        public ActionResult Info()
        {
            return View();
        }

        
    }
}

Web/LearningSystem.Web/Controllers/TestController.cs
namespace LearningSystem.Web.Controllers
{
    using System.Web.Mvc;
    using LearningSystem.Data;
    using LearningSystem.Services.Infrastructure.Contracts;

    [RoutePrefix("test")]
    public class TestController : BaseController
    {
        private IStudyService studyService;

        public TestController(ILearningSystemData data, IStudyService studyService) 
            : base(data)
        {
            this.studyService = studyService;
        }

        // GET: Test
        public ActionResult Index()
        {
            var allSections = studyService.GetAllSections();

            return View(allSections);
        }

        [Route("statistic")]
        public ActionResult Statistic()
        {
            return View();
        }
    }
}

Web/LearningSystem.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Learning System</title>
    @Styles.Render("~/Content/Site.css")
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")

    <meta name="description" content="MTA exam 98-361" />
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
            </div>
            <div class="navbar-collapse collapse">
                @if (User.Identity.IsAuthenticated)
                {
                    <ul class="nav navbar-nav">

                        <li>@Html.ActionLink("Home", "Index", "Home", new { area = string.Empty }, null)</li>
                        <li>@Html.ActionLink("Study", "AllMaterials", "StudyMaterial", new { area = string.Empty }, null)</li>
                        <li>@Html.ActionLink("Questions", "Index", "Questions", new { area = string.Empty }, null)</li>
                        <li>@Html.ActionLink("Statistic", "Statistic", "Test", new { area = string.Empty }, null)</li>
                        <li>@Html.ActionLink("Contacts", "Contact", "Home", new { area = string.Empty }, null)</li>
                    </ul>
                }
                else
                {
                    <ul class="nav navbar-nav navbar-left">
                        <li>@Html.ActionLink("Learning System", "Index", "Home", new { area = string.Empty }, null)</li>
                    </ul>

                }

                <ul class="nav navbar-nav navbar-left">
                    <li>@Html.ActionLink("Discussion", "Discussion", "Certification", new { area = string.Empty }, null)</li>
                </ul>

                @if (User.Identity.IsAuthenticated && User.IsInRole(GlobalConstants.AdminRole))
                {
                    <ul class="nav navbar-nav navbar-left">
                        <li>
                            <div class="dropdown">
                                <button class="btn btn-primary dropdown-toggle" type="button" data-toggle="dropdown" >
                                    Administration
                                    <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu">
                                    <li class="dropdown-header">Edit</li>
                                    <li>@Html.ActionLink("Materials", "Index", "AdminMaterials", new { area = "Administration" }, null)</li>
                                    <li>@Html.ActionLink("Comments", "Index", "AdminComments", new {area = "Administration"}, null)</li>
                                </ul>
                            </div>
                        </li>
                        
                    </ul>
                    
                }


                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @Html.Partial("_Notifications")
        @RenderBody()
        <hr />
        <footer class="text-center">
            <p>&copy; @DateTime.Now.Year - Project Assignment for the ASP.NET MVC Course @@ SoftUni </p>
            <p><a href="https://github.com/gabbriela/LearningSystem" target="blank">Project Source Code</a> </p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

Web/LearningSystem.Web/Views/Shared/_Notifications.cshtml
@using LearningSystem.Web.Extensions

@{
    var errorList = Html.GetNotifications(NotificationType.ERROR);
    var warningList = Html.GetNotifications(NotificationType.WARNING);
    var successList = Html.GetNotifications(NotificationType.SUCCESS);
    var infoList = Html.GetNotifications(NotificationType.INFO);
}
<!-- display errors -->
@if (errorList != null)
{
    <div class="alert alert-danger alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(errorList.Count() > 1){
            <strong><span class="glyphicon glyphicon-remove"></span> There are @errorList.Count() errors: </strong>
            <ul>
                @foreach (String message in errorList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-remove"></span> Error: </strong>
            @Html.Raw(errorList.First())
        }
    </div>
}

<!-- display warnings -->
@if (warningList != null)
{
    <div class="alert alert-warning alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(warningList.Count() > 1){
            <strong><span class="glyphicon glyphicon-warning-sign"></span> There are @warningList.Count() warnings: </strong>
            <ul>
                @foreach (String message in warningList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-warning-sign"></span> Warning: </strong>
            @Html.Raw(warningList.First())
        }
    </div>
}

<!-- display success -->
@if (successList != null)
{
    <div class="alert alert-success alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(successList.Count() > 1){
            <strong><span class="glyphicon glyphicon-ok"></span> There are @successList.Count() successful notifications: </strong>
            <ul>
                @foreach (String message in successList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-ok"></span> Success! </strong>
            @Html.Raw(successList.First())
        }
    </div>
}

<!-- display success -->
@if (infoList != null)
{
    <div class="alert alert-info alert-dismissable">
        <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
        @if(infoList.Count() > 1){
            <strong><span class="glyphicon glyphicon-info-sign"></span> There are @infoList.Count() notifications: </strong>
            <ul>
                @foreach (String message in infoList)
                {
                    <li>@Html.Raw(message)</li>
                }
            </ul>
        }
        else{
            <strong><span class="glyphicon glyphicon-info-sign"></span> </strong>
            @Html.Raw(infoList.First())
        }
    </div>
}

Web/LearningSystem.Web/Views/Shared/_PostCommentPartial.cshtml
@model LearningSystem.ViewModels.Comments.PostCommentViewModel

 @using (Ajax.BeginForm("PostComment", "Comments", 
     new AjaxOptions
     {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.InsertBefore,
        UpdateTargetId = "comments"
     }))
 {

     @Html.AntiForgeryToken()

     @Html.HiddenFor(m => m.MaterialId)
     @Html.EditorFor(m => m.Content)


     <input type="submit" class="btn btn-default"/>
     
 } 